// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "triggerMode": string;
      "triggerDebounce": number;
      "onlineDictSources": string;
      "ankiEnabled": boolean;
      "ankiConnectUrl": string;
      "ankiDeck": string;
      "ankiNoteType": string;
      "ankiFieldMap": string;
      "ankiAutoAdd": boolean;
      "ankiDup": string;
      "ankiDupScope": string;
      "ankiTags": string;
      "popupWidth": number;
      "popupMaxHeight": number;
      "sentenceExpand": boolean;
      "showCite": boolean;
      "edgeTtsFallback": boolean;
    };
  }
}
